package mjt.resdbc;

import static mjt.resdbc.ConvertDatabaseCreateColumnDefineSQL.getColumnDefineClauses;
import static mjt.resdbc.RoomCodeCommonUtils.swapEnclosersForRoom;

public class ConvertedDatabaseCreateVirtualTableSQL {

    private static final String CREATESTART = "CREATE VIRTUAL TABLE IF NOT EXISTS /*GENERATED BY CONVERT*/ ";
    private static final String CREATEDEFINESTART = "(";
    private static final String CREATEDEFINEEND = ")";

    public static String createVirtualTableCreateSQL(PreExistingFileDBInspect pefdbi, TableInfo ti) {
        StringBuilder crtsql = new StringBuilder();
        String tableNameToCode = swapEnclosersForRoom(ti.getEnclosedTableName());
        if (tableNameToCode.length() < 1) {
            tableNameToCode = ti.getTableName();
        }
        crtsql.append(CREATESTART);
        crtsql.append(tableNameToCode).append(" ");
        crtsql.append(SQLiteConstants.KEYWORD_USING).append(" ");
        crtsql.append(ti.getVirtualTableModule()).append(CREATEDEFINESTART);
        crtsql.append(getColumnDefineClauses(ti)).append(CREATEDEFINEEND);
        return crtsql.toString();
    }
}
